In [14]:
from helper_functions import combine_data, get_decoded_data_and_analyse, preprocess_data

import sys
import os
sys.path.append(os.path.abspath('..'))



# define the variables
file_path = "/Users/pza/OneDrive - Oak Ridge National Laboratory/Projects/VA Project/Project/Samhsa/data_clean/*.csv"
predictors = ['Year','CATAG6_decode', 'IRSEX_decode', 'NEWRACE2_decode', 'IRMARIT_decode', 'EDUHIGHCAT_decode', 'POVERTY3_decode', 'UD5ILALANY_decode', 'SPDPSTMON_decode', 'SPDPSTYR_decode', 'RCVSUTOMHT_decode', 'AMDEYR_decode', 'IRWRKSTAT18_decode', 'INCOME_decode', 'Health_Coverage_decode','COUTYP4_decode', 'IRPYUD5ALC_decode','IRPYUD5MRJ_decode', 'STMWYNORX_decode', 'SEDWYNORX_decode','IRPYUD5COC_decode', 'IRPYUD5HER_decode', 'IRPYUD5HAL_decode', 'IRPYUD5INH_decode', 'OXYCNANYYR_decode', 'UD5ILLANY_decode', 'BNGDRKMON_decode', 'HVYDRKMON_decode', 'IRIMPRESP_decode', 'AD_MDEA6_decode', 'AD_MDEA7_decode', 'BMI2_decode' ]
outcomes = ['ADSUITPAYR', 'IRSUICTHNK', 'IRSUIPLANYR' , 'IRSUITRYYR']

# define the categorical and binary columns for preprocessing
binary_columns = ["UD5ILALANY", "SPDPSTMON", "SPDPSTYR", "RCVSUTOMHT", "AMDEYR", "IRPYUD5ALC", "IRPYUD5MRJ", "STMWYNORX", "SEDWYNORX", "IRPYUD5COC", "IRPYUD5HER", "IRPYUD5HAL", "IRPYUD5INH", "OXYCNANYYR", "UD5ILLANY", "BNGDRKMON", "HVYDRKMON", "IRIMPRESP", "AD_MDEA6", "AD_MDEA7"]
categorical_columns = ['CATAG6', 'IRSEX', 'NEWRACE2', 'IRMARIT', 'EDUHIGHCAT', 'POVERTY3',  'IRWRKSTAT18', 'INCOME', 'Health_Coverage','COUTYP4' , 'BMI2']

column_dict = {
    "CATAG6":"Age",
    "IRSEX":"Gender",
    "NEWRACE2":"Race",
    
    "IRMARIT":"Marital Status",
    "EDUHIGHCAT":"Education",	
    "POVERTY3":"Poverty",
    "IRWRKSTAT18":"Employment Status",
    "INCOME":"Family Income",
    "Health_Coverage":"Health Insurance",
    "COUTYP4":"Urban Residence",
    "BMI2":"BMI",
    "UD5ILALANY":"Drug or Alcohol Use Disorder (any past year)",
    "SPDPSTMON":"Serious Psychological Distress (any past month)",
    "SPDPSTYR":"Serious Psychological Distress (any past year)",
    "RCVSUTOMHT":"Received Substance Use or Mental Health Treatment (any past year)",
    "AMDEYR":"Major Depressive Episode (any past year)",
    "IRPYUD5ALC":"Alcohol Use Disorder (any past year)",
    "IRPYUD5MRJ":"Marijuana Use Disorder (any past year)",
    "STMWYNORX":"Stimulant Use w/o RX (any past year)",
    "SEDWYNORX":"Sedative Use w/o RX (any past year)",
    "IRPYUD5COC":"Cocaine Use Disorder (any past year)",
    "IRPYUD5HER":"Heroin Use Disorder (any past year)",
    "IRPYUD5HAL":"Hallucinogen Use Disorder (any past year)",
    "IRPYUD5INH":"Inhalant Use Disorder (any past year)",
    "OXYCNANYYR":"Oxycontin Use (any past year)",
    "UD5ILLANY":"Drug Use Disorder (any past year)",
    "BNGDRKMON":"Binge Alcohol Use (any past month)",
    "HVYDRKMON":"Heavy Alcohol Use (any past month)",
    "IRIMPRESP":"Difficulty in Work Response (any past year)",
    "AD_MDEA6":"Felt Tired/Low Energy (nearly every day)",
    "AD_MDEA7":"Felt Worthless (nearly every day)"
}

In [15]:
# combine all the CSV files from multiple years into a single DataFrame. 
# Containing decoded data and original data
# we will need the original data for the analysis
# and the decoded data for the machine learning model
data = combine_data(file_path)
data.columns

Index(['QUESTID2', 'CATAG6', 'IRSEX', 'NEWRACE2', 'IRMARIT', 'EDUHIGHCAT',
       'POVERTY3', 'UD5ILALANY', 'SPDPSTMON', 'SPDPSTYR', 'RCVSUTOMHT',
       'ADSUITPAYR', 'BMI2', 'AMDEYR', 'IRWRKSTAT18', 'INCOME',
       'Health_Coverage', 'COUTYP4', 'IRPYUD5ALC', 'IRPYUD5MRJ', 'STMWYNORX',
       'SEDWYNORX', 'IRPYUD5COC', 'IRPYUD5HER', 'IRPYUD5HAL', 'IRPYUD5INH',
       'OXYCNANYYR', 'UD5ILLANY', 'BNGDRKMON', 'HVYDRKMON', 'IRINSUR4',
       'IRIMPRESP', 'AD_MDEA6', 'AD_MDEA7', 'IRSUICTHNK', 'IRSUIPLANYR',
       'IRSUITRYYR', 'BMI2_decode', 'CATAG6_decode', 'IRSEX_decode',
       'NEWRACE2_decode', 'IRMARIT_decode', 'EDUHIGHCAT_decode',
       'POVERTY3_decode', 'UD5ILALANY_decode', 'SPDPSTMON_decode',
       'SPDPSTYR_decode', 'RCVSUTOMHT_decode', 'AMDEYR_decode',
       'IRWRKSTAT18_decode', 'INCOME_decode', 'Health_Coverage_decode',
       'COUTYP4_decode', 'IRPYUD5ALC_decode', 'IRPYUD5MRJ_decode',
       'STMWYNORX_decode', 'SEDWYNORX_decode', 'IRPYUD5COC_decode',
       'IRPYUD5HER_decode', 'IRPYUD5HAL_decode', 'IRPYUD5INH_decode',
       'OXYCNANYYR_decode', 'UD5ILLANY_decode', 'BNGDRKMON_decode',
       'HVYDRKMON_decode', 'IRINSUR4_decode', 'IRIMPRESP_decode',
       'AD_MDEA6_decode', 'AD_MDEA7_decode', 'Year'],
      dtype='object')

In [16]:
# get only decoded data and count everything that is in the predictors and outcomes
data_selected = get_decoded_data_and_analyse(data, column_dict, predictors, outcomes)
data_selected

Data values counts:
Year
2022    47076
2021    45752
2023    45122
2015    42899
2018    42285
2016    41867
2019    41867
2017    41858
2014    40935
2013    36599
2020    26084
Name: count, dtype: int64
CATAG6_decode
18-25 Years Old    145755
35-49 Years Old    119200
26-34 Years Old     91035
50-64 Years Old     53219
65 or Older         43135
Name: count, dtype: int64
IRSEX_decode
Female    245559
Male      206785
Name: count, dtype: int64
NEWRACE2_decode
NonHisp White                      275342
Hispanic                            76762
NonHisp Black/Afr Am                53972
NonHisp Asian                       22248
NonHisp more than                   15573
NonHisp Native Am/AK Native          6246
NonHisp Native HI/Other Pac Isl      2201
Name: count, dtype: int64
IRMARIT_decode
Never Been Married       203940
Married                  187066
Divorced or Separated     47733
Widowed                   13605
Name: count, dtype: int64
EDUHIGHCAT_decode
Some coll/Assoc Dg    141506
College graduate      136202
High school grad      119872
Less high school       54764
Name: count, dtype: int64
POVERTY3_decode
Income More Than 2X Fed Pov Thresh    276122
Income Up to 2X Fed Pov Thresh         93500
Living in Poverty                      82722
Name: count, dtype: int64
UD5ILALANY_decode
Yes    251244
No     201100
Name: count, dtype: int64
SPDPSTMON_decode
No     412851
Yes     39493
Name: count, dtype: int64
SPDPSTYR_decode
No     376881
Yes     75463
Name: count, dtype: int64
RCVSUTOMHT_decode
No     365440
Yes     86904
Name: count, dtype: int64
AMDEYR_decode
No     408955
Yes     43389
Name: count, dtype: int64
IRWRKSTAT18_decode
Employed full time    231981
Other                 122004
Employed part time     70723
Unemployed             27636
Name: count, dtype: int64
INCOME_decode
$75,000 or More      160301
$20,000 - $49,999    135919
Less than $20,000     85658
$50,000 - $74,999     70466
Name: count, dtype: int64
Health_Coverage_decode
Private plan     282755
Medicaid/CHIP     75800
Uninsured         55037
Other             21777
Medicare          16975
Name: count, dtype: int64
COUTYP4_decode
Large Metropolitan    203688
Small Metropolitan    164328
Nonmetropolitan        84328
Name: count, dtype: int64
IRPYUD5ALC_decode
Yes    232169
No     220175
Name: count, dtype: int64
IRPYUD5MRJ_decode
No     378624
Yes     73720
Name: count, dtype: int64
STMWYNORX_decode
No     443243
Yes      9101
Name: count, dtype: int64
SEDWYNORX_decode
No     451009
Yes      1335
Name: count, dtype: int64
IRPYUD5COC_decode
No     443131
Yes      9213
Name: count, dtype: int64
IRPYUD5HER_decode
No     450437
Yes      1907
Name: count, dtype: int64
IRPYUD5HAL_decode
No     443062
Yes      9282
Name: count, dtype: int64
IRPYUD5INH_decode
No     450149
Yes      2195
Name: count, dtype: int64
OXYCNANYYR_decode
No     439886
Yes     12458
Name: count, dtype: int64
UD5ILLANY_decode
No     362811
Yes     89533
Name: count, dtype: int64
BNGDRKMON_decode
No     320365
Yes    131979
Name: count, dtype: int64
HVYDRKMON_decode
No     417673
Yes     34671
Name: count, dtype: int64
IRIMPRESP_decode
No     295654
Yes    156690
Name: count, dtype: int64
AD_MDEA6_decode
No     374572
Yes     77772
Name: count, dtype: int64
AD_MDEA7_decode
No     403460
Yes     48884
Name: count, dtype: int64
BMI2_decode
Healthy           148547
Overweight        131487
Obesity           114672
Severe Obesity     25684
Unknown            21015
Underweight        10939
Name: count, dtype: int64
ADSUITPAYR
0.0    423464
1.0     28880
Name: count, dtype: int64
IRSUICTHNK
0.0    423704
1.0     28640
Name: count, dtype: int64
IRSUIPLANYR
0.0    443242
1.0      9065
Name: count, dtype: int64
IRSUITRYYR
0.0    448121
1.0      4194
Name: count, dtype: int64

Data types of each column:
Year                        int64
CATAG6_decode              object
IRSEX_decode               object
NEWRACE2_decode            object
IRMARIT_decode             object
EDUHIGHCAT_decode          object
POVERTY3_decode            object
UD5ILALANY_decode          object
SPDPSTMON_decode           object
SPDPSTYR_decode            object
RCVSUTOMHT_decode          object
AMDEYR_decode              object
IRWRKSTAT18_decode         object
INCOME_decode              object
Health_Coverage_decode     object
COUTYP4_decode             object
IRPYUD5ALC_decode          object
IRPYUD5MRJ_decode          object
STMWYNORX_decode           object
SEDWYNORX_decode           object
IRPYUD5COC_decode          object
IRPYUD5HER_decode          object
IRPYUD5HAL_decode          object
IRPYUD5INH_decode          object
OXYCNANYYR_decode          object
UD5ILLANY_decode           object
BNGDRKMON_decode           object
HVYDRKMON_decode           object
IRIMPRESP_decode           object
AD_MDEA6_decode            object
AD_MDEA7_decode            object
BMI2_decode                object
ADSUITPAYR                float64
IRSUICTHNK                float64
IRSUIPLANYR               float64
IRSUITRYYR                float64
dtype: object

/Users/pza/Library/CloudStorage/OneDrive-OakRidgeNationalLaboratory/Projects/VA Project/Project/Samhsa/NSDUH_code/src/helper_functions.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_selected.rename(columns=column_dict, inplace=True)

,Year,Age,Gender,Race,Marital Status,Education,Poverty,Drug or Alcohol Use Disorder (any past year),Serious Psychological Distress (any past month),Serious Psychological Distress (any past year),...,Binge Alcohol Use (any past month),Heavy Alcohol Use (any past month),Difficulty in Work Response (any past year),Felt Tired/Low Energy (nearly every day),Felt Worthless (nearly every day),BMI,ADSUITPAYR,IRSUICTHNK,IRSUIPLANYR,IRSUITRYYR
0,2017,65 or Older,Male,NonHisp White,Married,College graduate,Income More Than 2X Fed Pov Thresh,Yes,No,No,...,No,No,Yes,No,No,Overweight,0.0,0.0,0.0,0.0
1,2017,35-49 Years Old,Male,NonHisp Black/Afr Am,Never Been Married,College graduate,Income More Than 2X Fed Pov Thresh,Yes,No,No,...,No,No,No,No,No,Overweight,0.0,0.0,0.0,0.0
2,2017,35-49 Years Old,Male,NonHisp Asian,Married,Some coll/Assoc Dg,Income More Than 2X Fed Pov Thresh,Yes,No,No,...,No,No,No,No,No,Overweight,0.0,0.0,0.0,0.0
3,2017,35-49 Years Old,Male,Hispanic,Married,College graduate,Income More Than 2X Fed Pov Thresh,Yes,No,No,...,No,No,No,No,No,Overweight,0.0,0.0,0.0,0.0
4,2017,65 or Older,Female,NonHisp White,Widowed,High school grad,Income More Than 2X Fed Pov Thresh,No,No,No,...,No,No,No,No,No,Healthy,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41862,2019,35-49 Years Old,Male,NonHisp White,Never Been Married,High school grad,Income Up to 2X Fed Pov Thresh,No,No,No,...,No,No,No,No,No,Obesity,0.0,0.0,0.0,0.0
41863,2019,26-34 Years Old,Female,NonHisp White,Married,College graduate,Income More Than 2X Fed Pov Thresh,Yes,No,Yes,...,No,No,Yes,No,No,Overweight,1.0,1.0,0.0,0.0
41864,2019,35-49 Years Old,Male,Hispanic,Married,Less high school,Income More Than 2X Fed Pov Thresh,No,No,No,...,No,No,No,No,No,Overweight,0.0,0.0,0.0,0.0
41865,2019,18-25 Years Old,Female,Hispanic,Never Been Married,Some coll/Assoc Dg,Income More Than 2X Fed Pov Thresh,Yes,No,No,...,Yes,No,No,No,No,Obesity,1.0,1.0,0.0,0.0
41866,2019,26-34 Years Old,Female,NonHisp Asian,Divorced or Separated,College graduate,Income More Than 2X Fed Pov Thresh,Yes,No,No,...,No,No,Yes,Yes,No,Underweight,0.0,0.0,0.0,0.0

# Think/plan/attempt to Suicide (ADSUITPAYR)

In [ ]:
# generating summary statistics table based on the selected predictors
df_selected = data_selected.copy()

predictors = []
df_selected["Age : SPD"] = df_selected["Age"] + " : " + df_selected["Serious Psychological Distress (any past year)"].astype(str)
predictors.append("Age : SPD")

df_selected["Sex : SPD"] = df_selected["Gender"] + " : " + df_selected["Serious Psychological Distress (any past year)"].astype(str)
predictors.append("Sex : SPD")

df_selected["Marital Status : SPD"] = df_selected["Marital Status"] + " : " + df_selected["Serious Psychological Distress (any past year)"].astype(str)
predictors.append("Marital Status : SPD")

df_selected["Urban Residence : Treatment"] = df_selected["Urban Residence"] + " : " + df_selected["Received Substance Use or Mental Health Treatment (any past year)"].astype(str)
predictors.append("Urban Residence : Treatment")

df_selected["BMI : SPD"] = df_selected["BMI"] + " : " + df_selected["Serious Psychological Distress (any past year)"].astype(str)
predictors.append("BMI : SPD")

In [21]:
outcome_len = df_selected.ADSUITPAYR.value_counts().shape[0]
statistics_table = []

for predictor in predictors:
    # for the first predictor, we need to calculate the statistics for all the data
    if predictor == "All":
        df_tmp = df_selected.copy()
        subgroup = ["All", "All"]
        
        for i in range(outcome_len):
            subgroup.append(df_tmp.ADSUITPAYR.value_counts()[i])
           
        subgroup.append(df_tmp.shape[0])
        statistics_table.append(subgroup)
     
    
    # for the rest of the predictors, we need to calculate the statistics for each subgroup
    else:
        # sorted list of distinct values of the predictor
        # Ensure all values in the column are strings for consistent sorting
        distinct_values = list(np.sort(df_selected[predictor].astype(str).unique()))
        for distinct_value in distinct_values:
            subgroup = [predictor, distinct_value]

            if predictor == "Year":  # if the predictor is Year, we need to convert the distinct value to int
                df_tmp = df_selected[df_selected[predictor] == int(distinct_value)]
            else:  # if the predictor is not Year, we can use the distinct value directly
                df_tmp = df_selected[df_selected[predictor] == distinct_value]
            

            for i in range(outcome_len):
                if df_tmp.shape[0] == 0:
                    subgroup.append([0])
                else:
                    try:
                        subgroup.append(df_tmp.ADSUITPAYR.value_counts()[i])
                        
                    except KeyError:  # if certain outcome value (for example 0 or 1) does not exist in the subgroup
                        subgroup.append(0)
                        
            subgroup.append(df_tmp.shape[0])
            statistics_table.append(subgroup)

In [22]:
statistics_table

[['Age:SPD', '18-25 Years Old:No', np.int64(105463), np.int64(3363), 108826],
 ['Age:SPD', '18-25 Years Old:Yes', np.int64(24734), np.int64(12195), 36929],
 ['Age:SPD', '26-34 Years Old:No', np.int64(72784), np.int64(1418), 74202],
 ['Age:SPD', '26-34 Years Old:Yes', np.int64(12594), np.int64(4239), 16833],
 ['Age:SPD', '35-49 Years Old:No', np.int64(102060), np.int64(1589), 103649],
 ['Age:SPD', '35-49 Years Old:Yes', np.int64(11925), np.int64(3626), 15551],
 ['Age:SPD', '50-64 Years Old:No', np.int64(48012), np.int64(693), 48705],
 ['Age:SPD', '50-64 Years Old:Yes', np.int64(3479), np.int64(1035), 4514],
 ['Age:SPD', '65 or Older:No', np.int64(41024), np.int64(475), 41499],
 ['Age:SPD', '65 or Older:Yes', np.int64(1389), np.int64(247), 1636],
 ['Gender:SPD', 'Female:No', np.int64(193123), np.int64(3729), 196852],
 ['Gender:SPD', 'Female:Yes', np.int64(35402), np.int64(13305), 48707],
 ['Gender:SPD', 'Male:No', np.int64(176220), np.int64(3809), 180029],
 ['Gender:SPD', 'Male:Yes', np.int64(18719), np.int64(8037), 26756],
 ['Marital Status:SPD',
  'Divorced or Separated:No',
  np.int64(38411),
  np.int64(837),
  39248],
 ['Marital Status:SPD',
  'Divorced or Separated:Yes',
  np.int64(6192),
  np.int64(2293),
  8485],
 ['Marital Status:SPD',
  'Married:No',
  np.int64(166477),
  np.int64(2089),
  168566],
 ['Marital Status:SPD', 'Married:Yes', np.int64(14480), np.int64(4020), 18500],
 ['Marital Status:SPD',
  'Never Been Married:No',
  np.int64(152335),
  np.int64(4437),
  156772],
 ['Marital Status:SPD',
  'Never Been Married:Yes',
  np.int64(32367),
  np.int64(14801),
  47168],
 ['Marital Status:SPD', 'Widowed:No', np.int64(12120), np.int64(175), 12295],
 ['Marital Status:SPD', 'Widowed:Yes', np.int64(1082), np.int64(228), 1310],
 ['Urban Residence:Treatment',
  'Large Metropolitan:No',
  np.int64(161243),
  np.int64(6034),
  167277],
 ['Urban Residence:Treatment',
  'Large Metropolitan:Yes',
  np.int64(30450),
  np.int64(5961),
  36411],
 ['Urban Residence:Treatment',
  'Nonmetropolitan:No',
  np.int64(65136),
  np.int64(2661),
  67797],
 ['Urban Residence:Treatment',
  'Nonmetropolitan:Yes',
  np.int64(13584),
  np.int64(2947),
  16531],
 ['Urban Residence:Treatment',
  'Small Metropolitan:No',
  np.int64(125130),
  np.int64(5236),
  130366],
 ['Urban Residence:Treatment',
  'Small Metropolitan:Yes',
  np.int64(27921),
  np.int64(6041),
  33962],
 ['BMI:SPD', 'Healthy:No', np.int64(120341), np.int64(2464), 122805],
 ['BMI:SPD', 'Healthy:Yes', np.int64(18550), np.int64(7192), 25742],
 ['BMI:SPD', 'Obesity:No', np.int64(93260), np.int64(1934), 95194],
 ['BMI:SPD', 'Obesity:Yes', np.int64(13768), np.int64(5710), 19478],
 ['BMI:SPD', 'Overweight:No', np.int64(111008), np.int64(2049), 113057],
 ['BMI:SPD', 'Overweight:Yes', np.int64(13524), np.int64(4906), 18430],
 ['BMI:SPD', 'Severe Obesity:No', np.int64(19081), np.int64(524), 19605],
 ['BMI:SPD', 'Severe Obesity:Yes', np.int64(4186), np.int64(1893), 6079],
 ['BMI:SPD', 'Underweight:No', np.int64(8194), np.int64(225), 8419],
 ['BMI:SPD', 'Underweight:Yes', np.int64(1750), np.int64(770), 2520],
 ['BMI:SPD', 'Unknown:No', np.int64(17459), np.int64(342), 17801],
 ['BMI:SPD', 'Unknown:Yes', np.int64(2343), np.int64(871), 3214]]

In [23]:
#df_statistics_table = pd.DataFrame(statistics_table)
import pandas
df_statistics_table = pd.DataFrame(statistics_table, columns=['Group', 'Group Value', "Y=0", "Y=1", "Total"])

In [24]:
df_statistics_table

,Group,Group Value,Y=0,Y=1,Total
0,Age:SPD,18-25 Years Old:No,105463,3363,108826
1,Age:SPD,18-25 Years Old:Yes,24734,12195,36929
2,Age:SPD,26-34 Years Old:No,72784,1418,74202
3,Age:SPD,26-34 Years Old:Yes,12594,4239,16833
4,Age:SPD,35-49 Years Old:No,102060,1589,103649
5,Age:SPD,35-49 Years Old:Yes,11925,3626,15551
6,Age:SPD,50-64 Years Old:No,48012,693,48705
7,Age:SPD,50-64 Years Old:Yes,3479,1035,4514
8,Age:SPD,65 or Older:No,41024,475,41499
9,Age:SPD,65 or Older:Yes,1389,247,1636
10,Gender:SPD,Female:No,193123,3729,196852
11,Gender:SPD,Female:Yes,35402,13305,48707
12,Gender:SPD,Male:No,176220,3809,180029
13,Gender:SPD,Male:Yes,18719,8037,26756
14,Marital Status:SPD,Divorced or Separated:No,38411,837,39248
15,Marital Status:SPD,Divorced or Separated:Yes,6192,2293,8485
16,Marital Status:SPD,Married:No,166477,2089,168566
17,Marital Status:SPD,Married:Yes,14480,4020,18500
18,Marital Status:SPD,Never Been Married:No,152335,4437,156772
19,Marital Status:SPD,Never Been Married:Yes,32367,14801,47168
20,Marital Status:SPD,Widowed:No,12120,175,12295
21,Marital Status:SPD,Widowed:Yes,1082,228,1310
22,Urban Residence:Treatment,Large Metropolitan:No,161243,6034,167277
23,Urban Residence:Treatment,Large Metropolitan:Yes,30450,5961,36411
24,Urban Residence:Treatment,Nonmetropolitan:No,65136,2661,67797
25,Urban Residence:Treatment,Nonmetropolitan:Yes,13584,2947,16531
26,Urban Residence:Treatment,Small Metropolitan:No,125130,5236,130366
27,Urban Residence:Treatment,Small Metropolitan:Yes,27921,6041,33962
28,BMI:SPD,Healthy:No,120341,2464,122805
29,BMI:SPD,Healthy:Yes,18550,7192,25742
30,BMI:SPD,Obesity:No,93260,1934,95194
31,BMI:SPD,Obesity:Yes,13768,5710,19478
32,BMI:SPD,Overweight:No,111008,2049,113057
33,BMI:SPD,Overweight:Yes,13524,4906,18430
34,BMI:SPD,Severe Obesity:No,19081,524,19605
35,BMI:SPD,Severe Obesity:Yes,4186,1893,6079
36,BMI:SPD,Underweight:No,8194,225,8419
37,BMI:SPD,Underweight:Yes,1750,770,2520
38,BMI:SPD,Unknown:No,17459,342,17801
39,BMI:SPD,Unknown:Yes,2343,871,3214

In [25]:
# save file 

save_file = "/Users/pza/OneDrive - Oak Ridge National Laboratory/Projects/VA Project/Project/Samhsa/outcomes/statistics_table/statistics_table_combined_ADSUITPAYR.csv"
df_statistics_table.to_csv(save_file, index=False)