In [51]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import glob

# Define the path where all CSV files are stored
#file_path = "path/to/your/csv/files/*.csv"  # Update this path
file_path = "/Users/pza/OneDrive - Oak Ridge National Laboratory/Projects/VA Project/Project/Samhsa/data_clean/*.csv"

In [52]:
# Read and merge all CSV files with a 'Year' column
dataframes = []
for file in glob.glob(file_path):
    df = pd.read_csv(file)
    year = file.split("_")[-1].split(".")[0]  # Extract year from filename (format "statistics_table_2013.csv")
    df["Year"] = int(year)
    dataframes.append(df)

In [53]:
# Combine all data
data = pd.concat(dataframes)

In [54]:
data.columns

Index(['QUESTID2', 'CATAG6', 'IRSEX', 'NEWRACE2', 'IRMARIT', 'EDUHIGHCAT',
       'POVERTY3', 'UD5ILALANY', 'SPDPSTMON', 'SPDPSTYR', 'RCVSUTOMHT',
       'ADSUITPAYR', 'BMI2', 'AMDEYR', 'IRWRKSTAT18', 'INCOME',
       'Health_Coverage', 'COUTYP4', 'IRPYUD5ALC', 'IRPYUD5MRJ', 'STMWYNORX',
       'SEDWYNORX', 'IRPYUD5COC', 'IRPYUD5HER', 'IRPYUD5HAL', 'IRPYUD5INH',
       'OXYCNANYYR', 'UD5ILLANY', 'BNGDRKMON', 'HVYDRKMON', 'IRINSUR4',
       'IRIMPRESP', 'AD_MDEA6', 'AD_MDEA7', 'IRSUICTHNK', 'IRSUIPLANYR',
       'IRSUITRYYR', 'BMI2_decode', 'CATAG6_decode', 'IRSEX_decode',
       'NEWRACE2_decode', 'IRMARIT_decode', 'EDUHIGHCAT_decode',
       'POVERTY3_decode', 'UD5ILALANY_decode', 'SPDPSTMON_decode',
       'SPDPSTYR_decode', 'RCVSUTOMHT_decode', 'AMDEYR_decode',
       'IRWRKSTAT18_decode', 'INCOME_decode', 'Health_Coverage_decode',
       'COUTYP4_decode', 'IRPYUD5ALC_decode', 'IRPYUD5MRJ_decode',
       'STMWYNORX_decode', 'SEDWYNORX_decode', 'IRPYUD5COC_decode',
       'IRPYUD5HER_decode', 'IRPYUD5HAL_decode', 'IRPYUD5INH_decode',
       'OXYCNANYYR_decode', 'UD5ILLANY_decode', 'BNGDRKMON_decode',
       'HVYDRKMON_decode', 'IRINSUR4_decode', 'IRIMPRESP_decode',
       'AD_MDEA6_decode', 'AD_MDEA7_decode', 'Year'],
      dtype='object')

In [55]:
data

,QUESTID2,CATAG6,IRSEX,NEWRACE2,IRMARIT,EDUHIGHCAT,POVERTY3,UD5ILALANY,SPDPSTMON,SPDPSTYR,...,IRPYUD5INH_decode,OXYCNANYYR_decode,UD5ILLANY_decode,BNGDRKMON_decode,HVYDRKMON_decode,IRINSUR4_decode,IRIMPRESP_decode,AD_MDEA6_decode,AD_MDEA7_decode,Year
0,55235143,6,1,1,1,4,3.0,1,0.0,0.0,...,No,No,No,No,No,Yes,Yes,No,No,2017
1,13435143,4,1,2,4,4,3.0,1,0.0,0.0,...,No,No,Yes,No,No,Yes,No,No,No,2017
2,81345143,4,1,5,1,3,3.0,1,0.0,0.0,...,No,No,No,No,No,Yes,No,No,No,2017
3,53955143,4,1,7,1,4,3.0,1,0.0,0.0,...,No,No,No,No,No,Yes,No,No,No,2017
4,51775143,6,2,1,2,2,3.0,0,0.0,0.0,...,No,No,No,No,No,Yes,No,No,No,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41862,39094730,4,1,1,4,2,2.0,0,0.0,0.0,...,No,No,No,No,No,No,No,No,No,2019
41863,61414730,3,2,1,1,4,3.0,1,0.0,1.0,...,No,No,Yes,No,No,Yes,Yes,No,No,2019
41864,49614730,4,1,7,1,1,3.0,0,0.0,0.0,...,No,No,No,No,No,No,No,No,No,2019
41865,29424730,2,2,7,4,3,3.0,1,0.0,0.0,...,No,No,Yes,Yes,No,Yes,No,No,No,2019
41866,71744730,3,2,5,3,4,3.0,1,0.0,0.0,...,No,No,No,No,No,No,Yes,Yes,No,2019

In [56]:
for y in [2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    print(f"Year: {y}")
    print(data[data["Year"] == y].shape[0])

Year: 2013
36599
Year: 2014
40935
Year: 2015
42899
Year: 2016
41867
Year: 2017
41858
Year: 2018
42285
Year: 2019
41867
Year: 2020
26084
Year: 2021
45752
Year: 2022
47076
Year: 2023
45122

In [57]:
# check if data have any missing values
missing_values = data.isnull().sum()
missing_values = missing_values[missing_values > 0]
print("Missing values in the dataset:")
print(missing_values)

Missing values in the dataset:
BMI2           14281
IRSUIPLANYR       37
IRSUITRYYR        29
dtype: int64

# Think/plan/attempt to Suicide (ADSUITPAYR)

In [63]:
# generating summary statistics table based on the selected predictors
df_selected = data.copy()
statistics_table = []
outcome_len = df_selected.ADSUITPAYR.value_counts().shape[0]


preds = df[['CATAG6', 'IRSEX', 'NEWRACE2', 'IRMARIT', 'EDUHIGHCAT', 'POVERTY3', 'UD5ILALANY', 'SPDPSTMON', 'SPDPSTYR', 'RCVSUTOMHT', 'AMDEYR', 'IRWRKSTAT18', 'INCOME', 'Health_Coverage','COUTYP4', 'IRPYUD5ALC','IRPYUD5MRJ', 'STMWYNORX', 'SEDWYNORX','IRPYUD5COC', 'IRPYUD5HER', 'IRPYUD5HAL', 'IRPYUD5INH', 'OXYCNANYYR', 'UD5ILLANY', 'BNGDRKMON', 'HVYDRKMON', 'IRINSUR4', 'IRIMPRESP', 'AD_MDEA6', 'AD_MDEA7' ]]

preds_decode = []
for p in preds:
    p_dict = str(p) + '_dict'
    p_decode = str(p) + '_decode'
    preds_decode.append(p_decode)

predictors = ["All", "Year"] + preds_decode + ["BMI2_decode"]
     
for predictor in predictors:
    # for the first predictor, we need to calculate the statistics for all the data
    if predictor == "All":
        df_tmp = df_selected.copy()
        subgroup = ["All", "All"]
        
        for i in range(outcome_len):
            subgroup.append(df_tmp.ADSUITPAYR.value_counts()[i])
           
        subgroup.append(df_tmp.shape[0])
        statistics_table.append(subgroup)
     
    
    # for the rest of the predictors, we need to calculate the statistics for each subgroup
    else:
        # sorted list of distinct values of the predictor
        # Ensure all values in the column are strings for consistent sorting
        distinct_values = list(np.sort(df_selected[predictor].astype(str).unique()))
        for distinct_value in distinct_values:
            subgroup = [predictor, distinct_value]

            if predictor == "Year":  # if the predictor is Year, we need to convert the distinct value to int
                df_tmp = df_selected[df_selected[predictor] == int(distinct_value)]
            else:  # if the predictor is not Year, we can use the distinct value directly
                df_tmp = df_selected[df_selected[predictor] == distinct_value]
            

            for i in range(outcome_len):
                if df_tmp.shape[0] == 0:
                    subgroup.append([0])
                else:
                    try:
                        subgroup.append(df_tmp.ADSUITPAYR.value_counts()[i])
                        
                    except KeyError:  # if certain outcome value (for example 0 or 1) does not exist in the subgroup
                        subgroup.append(0)
                        
            subgroup.append(df_tmp.shape[0])
            statistics_table.append(subgroup)

In [66]:
#df_statistics_table = pd.DataFrame(statistics_table)
df_statistics_table = pd.DataFrame(statistics_table, columns=['Group', 'Group Value', "Y=0", "Y=1", "Total"])

In [67]:
df_statistics_table

           Group     Group Value     Y=0    Y=1   Total
0            All             All  423464  28880  452344
1           Year            2013   34519   2080   36599
2           Year            2014   38886   2049   40935
3           Year            2015   40539   2360   42899
4           Year            2016   39519   2348   41867
..           ...             ...     ...    ...     ...
96   BMI2_decode         Obesity  107028   7644  114672
97   BMI2_decode      Overweight  124532   6955  131487
98   BMI2_decode  Severe Obesity   23267   2417   25684
99   BMI2_decode     Underweight    9944    995   10939
100  BMI2_decode         Unknown   19802   1213   21015

[101 rows x 5 columns]

In [68]:
# save file 

save_file = "/Users/pza/OneDrive - Oak Ridge National Laboratory/Projects/VA Project/Project/Samhsa/outcomes/statistics_table/statistics_table_ADSUITPAYR.csv"
df_statistics_table.to_csv(save_file, index=False)

# Think about Suicide (IRSUICTHNK)

In [69]:
# generating summary statistics table based on the selected predictors
df_selected = data.copy()
# Filter out rows where 'IRSUICTHNK' is null
df_selected = df_selected[df_selected['IRSUICTHNK'].notnull()]

statistics_table = []
outcome_len = df_selected.IRSUICTHNK.value_counts().shape[0]


preds = df[['CATAG6', 'IRSEX', 'NEWRACE2', 'IRMARIT', 'EDUHIGHCAT', 'POVERTY3', 'UD5ILALANY', 'SPDPSTMON', 'SPDPSTYR', 'RCVSUTOMHT', 'AMDEYR', 'IRWRKSTAT18', 'INCOME', 'Health_Coverage','COUTYP4', 'IRPYUD5ALC','IRPYUD5MRJ', 'STMWYNORX', 'SEDWYNORX','IRPYUD5COC', 'IRPYUD5HER', 'IRPYUD5HAL', 'IRPYUD5INH', 'OXYCNANYYR', 'UD5ILLANY', 'BNGDRKMON', 'HVYDRKMON', 'IRINSUR4', 'IRIMPRESP', 'AD_MDEA6', 'AD_MDEA7']]

preds_decode = []
for p in preds:
    p_dict = str(p) + '_dict'
    p_decode = str(p) + '_decode'
    preds_decode.append(p_decode)

predictors = ["All", "Year"] + preds_decode + ["BMI2_decode"]
     
for predictor in predictors:
    # for the first predictor, we need to calculate the statistics for all the data
    if predictor == "All":
        df_tmp = df_selected.copy()
        subgroup = ["All", "All"]
        
        for i in range(outcome_len):
            subgroup.append(df_tmp.IRSUICTHNK.value_counts()[i])
            
        subgroup.append(df_tmp.shape[0])
        statistics_table.append(subgroup)
     
    
    # for the rest of the predictors, we need to calculate the statistics for each subgroup
    else:
        # sorted list of distinct values of the predictor
        # Ensure all values in the column are strings for consistent sorting
        distinct_values = list(np.sort(df_selected[predictor].astype(str).unique()))
        for distinct_value in distinct_values:
            subgroup = [predictor, distinct_value]

            if predictor == "Year":  # if the predictor is Year, we need to convert the distinct value to int
                df_tmp = df_selected[df_selected[predictor] == int(distinct_value)]
            else:  # if the predictor is not Year, we can use the distinct value directly
                df_tmp = df_selected[df_selected[predictor] == distinct_value]
            

            for i in range(outcome_len):
                if df_tmp.shape[0] == 0:
                    subgroup.append([0])
                else:
                    try:
                        subgroup.append(df_tmp.IRSUICTHNK.value_counts()[i])
                        
                    except KeyError:  # if certain outcome value (for example 0 or 1) does not exist in the subgroup
                        subgroup.append(0)
                        
            subgroup.append(df_tmp.shape[0])
            statistics_table.append(subgroup)

In [70]:
df_statistics_table = pd.DataFrame(statistics_table, columns=['Group', 'Group Value', "Y=0", "Y=1", "Total"])
save_file = "/Users/pza/OneDrive - Oak Ridge National Laboratory/Projects/VA Project/Project/Samhsa/outcomes/statistics_table/statistics_table_IRSUICTHNK.csv"
df_statistics_table.to_csv(save_file, index=False)

# Plan about Suicide (IRSUIPLANYR)

In [71]:
# generating summary statistics table based on the selected predictors
df_selected = data.copy()
statistics_table = []
# Filter out rows where 'IRSUIPLANYR' is null
df_selected = df_selected[df_selected['IRSUIPLANYR'].notnull()]

outcome_len = df_selected.IRSUIPLANYR.value_counts().shape[0]


preds = df[['CATAG6', 'IRSEX', 'NEWRACE2', 'IRMARIT', 'EDUHIGHCAT', 'POVERTY3', 'UD5ILALANY', 'SPDPSTMON', 'SPDPSTYR', 'RCVSUTOMHT', 'AMDEYR', 'IRWRKSTAT18', 'INCOME', 'Health_Coverage','COUTYP4', 'IRPYUD5ALC','IRPYUD5MRJ', 'STMWYNORX', 'SEDWYNORX','IRPYUD5COC', 'IRPYUD5HER', 'IRPYUD5HAL', 'IRPYUD5INH', 'OXYCNANYYR', 'UD5ILLANY', 'BNGDRKMON', 'HVYDRKMON', 'IRINSUR4', 'IRIMPRESP', 'AD_MDEA6', 'AD_MDEA7' ]]

preds_decode = []
for p in preds:
    p_dict = str(p) + '_dict'
    p_decode = str(p) + '_decode'
    preds_decode.append(p_decode)

predictors = ["All", "Year"] + preds_decode + ["BMI2_decode"]
     
for predictor in predictors:
    # for the first predictor, we need to calculate the statistics for all the data
    if predictor == "All":
        df_tmp = df_selected.copy()
        subgroup = ["All", "All"]
        
        for i in range(outcome_len):
            subgroup.append(df_tmp.IRSUIPLANYR.value_counts()[i])
            
        subgroup.append(df_tmp.shape[0])
        statistics_table.append(subgroup)
     
    
    # for the rest of the predictors, we need to calculate the statistics for each subgroup
    else:
        # sorted list of distinct values of the predictor
        # Ensure all values in the column are strings for consistent sorting
        distinct_values = list(np.sort(df_selected[predictor].astype(str).unique()))
        for distinct_value in distinct_values:
            subgroup = [predictor, distinct_value]

            if predictor == "Year":  # if the predictor is Year, we need to convert the distinct value to int
                df_tmp = df_selected[df_selected[predictor] == int(distinct_value)]
            else:  # if the predictor is not Year, we can use the distinct value directly
                df_tmp = df_selected[df_selected[predictor] == distinct_value]
            

            for i in range(outcome_len):
                if df_tmp.shape[0] == 0:
                    subgroup.append([0])
                else:
                    try:
                        subgroup.append(df_tmp.IRSUIPLANYR.value_counts()[i])
                        
                    except KeyError:  # if certain outcome value (for example 0 or 1) does not exist in the subgroup
                        subgroup.append(0)
                        
            subgroup.append(df_tmp.shape[0])
            statistics_table.append(subgroup)

In [72]:
df_statistics_table = pd.DataFrame(statistics_table, columns=['Group', 'Group Value', "Y=0", "Y=1", "Total"])
save_file = "/Users/pza/OneDrive - Oak Ridge National Laboratory/Projects/VA Project/Project/Samhsa/outcomes/statistics_table/statistics_table_IRSUIPLANYR.csv"
df_statistics_table.to_csv(save_file, index=False)

# Attemp to Suicide (IRSUITRYYR)

In [73]:
# generating summary statistics table based on the selected predictors
df_selected = data.copy()
statistics_table = []

# Filter out rows where 'IRSUITRYYR' is null
df_selected = df_selected[df_selected['IRSUITRYYR'].notnull()]


outcome_len = df_selected.IRSUITRYYR.value_counts().shape[0]


preds = df[['CATAG6', 'IRSEX', 'NEWRACE2', 'IRMARIT', 'EDUHIGHCAT', 'POVERTY3', 'UD5ILALANY', 'SPDPSTMON', 'SPDPSTYR', 'RCVSUTOMHT', 'AMDEYR', 'IRWRKSTAT18', 'INCOME', 'Health_Coverage','COUTYP4', 'IRPYUD5ALC','IRPYUD5MRJ', 'STMWYNORX', 'SEDWYNORX','IRPYUD5COC', 'IRPYUD5HER', 'IRPYUD5HAL', 'IRPYUD5INH', 'OXYCNANYYR', 'UD5ILLANY', 'BNGDRKMON', 'HVYDRKMON', 'IRINSUR4', 'IRIMPRESP', 'AD_MDEA6', 'AD_MDEA7' ]]

preds_decode = []
for p in preds:
    p_dict = str(p) + '_dict'
    p_decode = str(p) + '_decode'
    preds_decode.append(p_decode)

predictors = ["All", "Year"] + preds_decode + ["BMI2_decode"]
     
for predictor in predictors:
    # for the first predictor, we need to calculate the statistics for all the data
    if predictor == "All":
        df_tmp = df_selected.copy()
        subgroup = ["All", "All"]
        
        for i in range(outcome_len):
            subgroup.append(df_tmp.IRSUITRYYR.value_counts()[i])
            #subgroup.append(round(df_tmp.IRSUITRYYR.value_counts()[i] / df_tmp.shape[0], 2))
        subgroup.append(df_tmp.shape[0])
        statistics_table.append(subgroup)
     
    
    # for the rest of the predictors, we need to calculate the statistics for each subgroup
    else:
        # sorted list of distinct values of the predictor
        # Ensure all values in the column are strings for consistent sorting
        distinct_values = list(np.sort(df_selected[predictor].astype(str).unique()))
        for distinct_value in distinct_values:
            subgroup = [predictor, distinct_value]

            if predictor == "Year":  # if the predictor is Year, we need to convert the distinct value to int
                df_tmp = df_selected[df_selected[predictor] == int(distinct_value)]
            else:  # if the predictor is not Year, we can use the distinct value directly
                df_tmp = df_selected[df_selected[predictor] == distinct_value]
            

            for i in range(outcome_len):
                if df_tmp.shape[0] == 0:
                    subgroup.append([0])
                else:
                    try:
                        subgroup.append(df_tmp.IRSUITRYYR.value_counts()[i])
                        #subgroup.append(round(df_tmp.IRSUITRYYR.value_counts()[i] / df_tmp.shape[0], 2))
                    except KeyError:  # if certain outcome value (for example 0 or 1) does not exist in the subgroup
                        subgroup.append(0)
                        #subgroup.append(0.0)
            subgroup.append(df_tmp.shape[0])
            statistics_table.append(subgroup)

In [74]:
df_statistics_table = pd.DataFrame(statistics_table, columns=['Group', 'Group Value', "Y=0", "Y=1", "Total"])
save_file = "/Users/pza/OneDrive - Oak Ridge National Laboratory/Projects/VA Project/Project/Samhsa/outcomes/statistics_table/statistics_table_IRSUITRYYR.csv"
df_statistics_table.to_csv(save_file, index=False)

In [7]:
x = 125130
y = 5236

print(x*100 / (x + y))  
print(y*100 / (x + y))

95.98361535983308
4.0163846401669145

In [ ]:
125130